addons:
  - selenium

before_script:
  # Exit one errors.
  - set -e

  # Install Behat
  - cd ./behat
  - cp behat.local.yml.shoov behat.local.yml
  - composer install

script:
  - ./bin/behat --tags=~wip

